In [2]:
import pandas as pd

def set_stats(path):
    import json
    with open(path, "r") as f:
        examples=[json.loads(line) for line in f]
    counter_ne = {"EVENT": 0, "TIME": 0, "DATE":0, "DURATION":0, "SET":0}
    counter_tr = {"AFTER": 0, "BEFORE": 0, "CONTAINS": 0, "DURING":0, "EQUALS":0, "IDENTITY":0, "OVERLAPS":0}
    counter_et = 0
    counter_et_tot = 0
    for example in examples:
        events = 0
        times = 0
        for entity in example['instances']:
            counter_ne[entity['type']] += 1
            if entity['type'] == 'EVENT':
                events += 1
            else:
                times += 1
        for relation in example['ee_temprels']:
            counter_tr[relation['rel']] += 1
        for et in example['event_times']:
            counter_et += 1
        counter_et_tot += events*times
    all = {**counter_ne, **counter_tr, "POS": counter_et, "NEG": counter_et_tot-counter_et}
    df = pd.DataFrame(all, index=[0])
    return df

train = set_stats("D:\\GeoTKG\\cleandata\\tie\\train.json")
test = set_stats("D:\\GeoTKG\\cleandata\\tie\\test.json")
valid = set_stats("D:\\GeoTKG\\cleandata\\tie\\eval.json")

pd.concat([train, test, valid], axis=0)

,EVENT,TIME,DATE,DURATION,SET,AFTER,BEFORE,CONTAINS,DURING,EQUALS,IDENTITY,OVERLAPS,POS,NEG
0,156576,2776,24766,4429,73,69204,68729,68213,2775,16305,35654,3779,52733,1132077
0,7678,111,941,166,23,795,1939,221,403,282,396,69,2464,88088
0,17215,317,2831,490,10,5856,5187,7421,273,1715,3684,343,5665,126363

In [33]:
def norm_set_stats(path):
    with open(path, "r") as f:
        examples=[json.loads(line) for line in f]
    counter_ne = {"TIME": 0, "DATE":0, "DURATION":0, "SET":0}

    for example in examples:
        type_ = example['input_text'].split('\n')[1][6:-1]
        counter_ne[type_] += 1
    return pd.DataFrame(counter_ne, index=[0])

train = norm_set_stats("C:\\Users\\hazza\\OneDrive\\Desktop\\GeoTKG\\cleandata\\normalise\\train.json")
test = norm_set_stats("C:\\Users\\hazza\\OneDrive\\Desktop\\GeoTKG\\cleandata\\normalise\\test.json")
valid = norm_set_stats("C:\\Users\\hazza\\OneDrive\\Desktop\\GeoTKG\\cleandata\\normalise\\eval.json")

pd.concat([train, test, valid], axis=0)

   TIME   DATE  DURATION  SET
0   382  12864      1711  135
0    47   1589       211   17
0    42   1430       190   15